# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas McCurdy
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

#paginate:         5

# Custom
baseurl:          /hyde
exclude:          ['Makefile', 'blog']
paginate_path:    "blog/page:num"
