# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas McCurdy
url:              http://nicolasmccurdy.github.io/

author:
  name:           Nicolas McCurdy
  url:            https://twitter.com/nicolasmccurdy

#paginate:         5

# Custom
baseurl:          /
exclude:          ['Makefile', 'blog']
paginate_path:    "blog/page:num"
