# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas McCurdy
url:              http://nicolasmccurdy.github.io
baseurl:          /

author:
  name:           Nicolas McCurdy
  url:            https://twitter.com/nicolasmccurdy

#paginate:         5

# Custom vars
version:          2.1.0
exclude:          ['Makefile', 'blog']
paginate_path:    "blog/page:num"

github:
  repo:           https://github.com/nicolasmccurdy/nicolasmccurdy.github.io
